//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEtfApi1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnalisisRiesgosConnect : DbContext
    {
        public AnalisisRiesgosConnect()
            : base("name=AnalisisRiesgosConnect")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Objetivo> Objetivoes { get; set; }
        public virtual DbSet<ObjetivosProyecto> ObjetivosProyectoes { get; set; }
        public virtual DbSet<Proyecto> Proyectoes { get; set; }
        public virtual DbSet<ProyectosEmpresa> ProyectosEmpresas { get; set; }
        public virtual DbSet<Riesgo> Riesgoes { get; set; }
        public virtual DbSet<RiesgosObjetivo> RiesgosObjetivoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<UsuariosEmpresa> UsuariosEmpresas { get; set; }
    }
}
