//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEtfApi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objetivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objetivo()
        {
            this.ObjetivosProyectoes = new HashSet<ObjetivosProyecto>();
            this.RiesgosObjetivoes = new HashSet<RiesgosObjetivo>();
        }
    
        public int IdObjetivo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int horasEstimadas { get; set; }
        public double costoHoraRecurso { get; set; }
        public double horasInvertidas { get; set; }
        public string nombreDelRecurso { get; set; }
        public bool estado { get; set; }
        public string porcentajeCompletitud { get; set; }
        public int IdProyecto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjetivosProyecto> ObjetivosProyectoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiesgosObjetivo> RiesgosObjetivoes { get; set; }
    }
}
