//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEtfApi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectosEmpresa
    {
        public int Id { get; set; }
        public int Fk_Proyecto { get; set; }
        public int Fk_Empresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
